name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    deploy:
      name: Setup Gcloud Account
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Add Asia Repo
        run: gcloud auth configure-docker asia-docker.pkg.dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:latest

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region asia-southeast1 --platform managed